### ISSUE TITLE
I don't really understand the purpose of this project

### ISSUE THREAD

**Issue by busybox11** [kunal1244/streams#4]
Hi!
I just checked your project because it was linked with Spotify, tried cloning it and installing it, but I don't know how to use it, and, more importantly, don't really know what is its purpose.

A better README with more explainations, screenshots and an install guide would be mich appreciated.

Keep up the good work!

**Comment by kunal1244** [comment]
Hey @busybox11 ! This is a pet project which is still under development, and though I am really looking forward to releasing a demo version, I haven't found the time really to finish this up. However, I'll add a README with a comprehensive guide, and list out a blueprint of how I want this application to shape up very soon.

Thank you for checking this out! I'll look forward to your feedback once the demo is out.
